# Generated by Django 3.2.8 on 2021-10-21 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Erabiltzailea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erabiltzailea', models.CharField(max_length=1000)),
                ('izena', models.CharField(max_length=1000)),
                ('abizena', models.CharField(max_length=1000)),
                ('posta', models.EmailField(max_length=1000)),
                ('pasahitza', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Jatetxea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=1000)),
                ('deskripzioa', models.CharField(max_length=1000)),
                ('helbidea', models.CharField(max_length=1000)),
                ('telefonoa', models.IntegerField()),
                ('mota', models.CharField(max_length=1000)),
                ('oharrak', models.CharField(max_length=1000)),
                ('img_path', models.CharField(max_length=1000)),
                ('distantzia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Saskia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helbidea', models.CharField(max_length=1000)),
                ('telefonoa', models.IntegerField()),
                ('data', models.DateTimeField()),
                ('erabiltzailea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erabiltzailea_saskia', to='jjm.erabiltzailea')),
            ],
        ),
        migrations.CreateModel(
            name='Produktua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=1000)),
                ('prezioa', models.FloatField()),
                ('mota', models.CharField(max_length=1000)),
                ('deskontua', models.BooleanField()),
                ('portzentaia', models.FloatField(blank=True, null=True)),
                ('img_path', models.CharField(max_length=1000)),
                ('jatetxea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jatetxea_produktua', to='jjm.jatetxea')),
            ],
        ),
        migrations.CreateModel(
            name='Iruzkina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testua', models.CharField(max_length=1000)),
                ('kalifikazioa', models.IntegerField()),
                ('erabiltzailea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erabiltzailea_iruzkina', to='jjm.erabiltzailea')),
                ('jatetxea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jatetxea_iruzkina', to='jjm.jatetxea')),
            ],
        ),
        migrations.CreateModel(
            name='Erosketa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kantitatea', models.IntegerField()),
                ('produktua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produktua_erosketa', to='jjm.produktua')),
                ('saskia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saskia', to='jjm.saskia')),
            ],
        ),
    ]
