# Generated by Django 3.2.8 on 2021-10-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjm', '0002_remove_jatetxea_oharrak'),
    ]

    operations = [
        migrations.AddField(
            model_name='jatetxea',
            name='latitud',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='jatetxea',
            name='longitud',
            field=models.FloatField(null=True),
        ),
    ]
