# Generated by Django 3.2.8 on 2021-10-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jjm', '0003_auto_20211021_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jatetxea',
            name='distantzia',
        ),
    ]
