# Generated by Django 3.2.8 on 2021-11-03 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jjm', '0004_remove_jatetxea_distantzia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iruzkina',
            name='erabiltzailea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erabiltzailea_iruzkina', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saskia',
            name='erabiltzailea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erabiltzailea_saskia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Erabiltzailea',
        ),
    ]
