# Generated by Django 3.2.8 on 2021-10-14 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saskia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helbidea', models.CharField(max_length=1000)),
                ('telefonoa', models.IntegerField(max_length=9)),
                ('data', models.DateTimeField()),
                ('erabiltzailea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saskia', to='blog.erabiltzailea')),
            ],
        ),
    ]
