# Generated by Django 3.2.8 on 2021-10-15 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_jatetxea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produktua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=1000)),
                ('prezioa', models.FloatField()),
                ('mota', models.CharField(max_length=1000)),
                ('deskontua', models.BooleanField()),
                ('portzentaia', models.FloatField()),
                ('img_path', models.CharField(max_length=1000)),
                ('jatetxea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jatetxea', to='blog.jatetxea')),
            ],
        ),
    ]
