# Generated by Django 3.2.8 on 2021-10-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_produktua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produktua',
            name='portzentaia',
            field=models.FloatField(null=True),
        ),
    ]
