# Generated by Django 3.2.8 on 2021-10-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_produktua_portzentaia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produktua',
            name='portzentaia',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
