# Generated by Django 3.2.8 on 2021-10-15 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_produktua_portzentaia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Erosketa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kantitatea', models.IntegerField()),
                ('produktua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produktua', to='blog.produktua')),
                ('saskia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saskia', to='blog.saskia')),
            ],
        ),
    ]
