# Generated by Django 3.2.8 on 2021-10-15 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_erosketa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erosketa',
            name='produktua',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produktua_erosketa', to='blog.produktua'),
        ),
        migrations.AlterField(
            model_name='jatetxea',
            name='izarrak',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jatetxea',
            name='telefonoa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produktua',
            name='jatetxea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jatetxea_produktua', to='blog.jatetxea'),
        ),
        migrations.AlterField(
            model_name='saskia',
            name='erabiltzailea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erabiltzailea_saskia', to='blog.erabiltzailea'),
        ),
        migrations.AlterField(
            model_name='saskia',
            name='telefonoa',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Iruzkina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testua', models.CharField(max_length=1000)),
                ('kalifikazioa', models.IntegerField()),
                ('erabiltzailea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erabiltzailea_iruzkina', to='blog.erabiltzailea')),
                ('produktua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produktua_iruzkina', to='blog.produktua')),
            ],
        ),
    ]
